source 'https://github.com/CocoaPods/Specs.git'

target 'Telegram-iOS-SDK', :exclusive => true do
  pod "Telegram-iOS-SDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Telegram-iOS-SDK", :path => "../"

  
end
